//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCVControldeErrores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCEPCIONES
    {
        public int IDEXCEPCION { get; set; }
        public string MENSAJE { get; set; }
        public string CONTROLADOR { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
